ingress-nginx:
  controller:
    service:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local
    replicaCount: 1

podinfo:
  ui:
    message: "It works as expected!"
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: 51.138.4.141.nip.io
        paths:
          - path: /
            pathType: ImplementationSpecific